# Generated by Django 4.2.8 on 2026-01-01 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hcm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ATR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_number", models.CharField(max_length=50, unique=True)),
                ("hiring_supervisor_name", models.CharField(max_length=200)),
                ("position_title", models.CharField(max_length=200)),
                ("roles_to_fill", models.IntegerField(default=1)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "required_skills",
                    models.TextField(
                        blank=True,
                        help_text="Required technical skills and competencies",
                    ),
                ),
                (
                    "required_experience",
                    models.TextField(
                        blank=True, help_text="Years and type of experience required"
                    ),
                ),
                (
                    "required_qualifications",
                    models.TextField(
                        blank=True,
                        help_text="Education level and certifications required",
                    ),
                ),
                (
                    "skill_sets",
                    models.TextField(
                        blank=True, help_text="Specific skill sets needed for the role"
                    ),
                ),
                ("budgeted", models.BooleanField(default=False)),
                (
                    "budget_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("zambian_junior", models.IntegerField(default=0)),
                ("zambian_senior", models.IntegerField(default=0)),
                ("expatriate", models.IntegerField(default=0)),
                ("use_internal_db", models.BooleanField(default=False)),
                ("internal_advertising", models.BooleanField(default=False)),
                ("external_advertising", models.BooleanField(default=False)),
                ("hr_db_search", models.BooleanField(default=False)),
                ("recruitment_agencies", models.BooleanField(default=False)),
                ("hr_manager_name", models.CharField(blank=True, max_length=200)),
                ("hr_manager_signed_at", models.DateField(blank=True, null=True)),
                ("ops_manager_name", models.CharField(blank=True, max_length=200)),
                ("ops_manager_signed_at", models.DateField(blank=True, null=True)),
                ("director_name", models.CharField(blank=True, max_length=200)),
                ("director_signed_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="hcm.department"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engaged_date", models.DateField()),
                ("name", models.CharField(max_length=200)),
                ("nrc", models.CharField(blank=True, max_length=50)),
                ("phone_number", models.CharField(blank=True, max_length=30)),
                ("position", models.CharField(max_length=200)),
                ("agreed_net_pay", models.CharField(blank=True, max_length=100)),
                ("accommodation", models.CharField(blank=True, max_length=200)),
                ("docs_submitted", models.BooleanField(default=False)),
                ("recommendation_date", models.DateField(blank=True, null=True)),
                ("interview_due_date", models.DateField(blank=True, null=True)),
                ("silicosis_status", models.CharField(blank=True, max_length=50)),
                ("medicals_status", models.CharField(blank=True, max_length=50)),
                ("ibf_status", models.CharField(blank=True, max_length=50)),
                (
                    "initial_induction_status",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "company_induction_status",
                    models.CharField(blank=True, max_length=50),
                ),
                ("site_permit_status", models.CharField(blank=True, max_length=50)),
                ("pit_permit_status", models.CharField(blank=True, max_length=50)),
                (
                    "pit_operation_permit_status",
                    models.CharField(blank=True, max_length=50),
                ),
                ("ohs_status", models.CharField(blank=True, max_length=50)),
                ("status", models.CharField(default="Pipeline", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "atr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidates",
                        to="recruitment.atr",
                    ),
                ),
            ],
            options={
                "ordering": ["-engaged_date"],
            },
        ),
    ]
