# Generated by Django 4.2.8 on 2026-01-01 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("FIXED_TERM", "Fixed-Term"),
                            ("PROBATION", "Probation"),
                            ("SHORT_TERM", "Short-Term"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "default_duration_months",
                    models.IntegerField(
                        blank=True,
                        help_text="Default duration for this contract type",
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Contract Types",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contractor_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent Staff"),
                            ("CONTRACT", "Contract Staff"),
                            ("CONTRACTOR", "External Contractor"),
                            ("CONSULTANT", "Consultant"),
                            ("TEMPORARY", "Temporary"),
                        ],
                        default="PERMANENT",
                        help_text="Employment classification",
                        max_length=20,
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "nrc",
                    models.CharField(
                        help_text="National Registration Card",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "nrc_number",
                    models.CharField(
                        blank=True, help_text="NRC unique portion", max_length=50
                    ),
                ),
                ("passport", models.CharField(blank=True, max_length=50)),
                (
                    "tpin",
                    models.CharField(
                        blank=True, help_text="Tax PIN", max_length=50, unique=True
                    ),
                ),
                (
                    "nhima",
                    models.CharField(
                        blank=True,
                        help_text="National Health Insurance Management Authority",
                        max_length=50,
                    ),
                ),
                (
                    "sss_number",
                    models.CharField(blank=True, help_text="S/S Number", max_length=50),
                ),
                (
                    "napsa_number",
                    models.CharField(
                        blank=True, help_text="NAPSA membership number", max_length=50
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("OTHER", "Other")],
                        max_length=10,
                    ),
                ),
                ("nationality", models.CharField(default="Zambian", max_length=100)),
                ("photo", models.ImageField(blank=True, upload_to="employee_photos/")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("house_address", models.TextField()),
                (
                    "residential_area",
                    models.CharField(
                        choices=[
                            ("KITWE", "Kitwe"),
                            ("CHINGOLA", "Chingola"),
                            ("NKANA", "Nkana"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=100,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "Suspended"),
                            ("ON_LEAVE", "On Leave"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("job_title", models.CharField(max_length=200)),
                ("point_of_hire", models.CharField(blank=True, max_length=100)),
                ("hire_date", models.DateField(db_index=True)),
                ("next_of_kin_name", models.CharField(blank=True, max_length=200)),
                (
                    "next_of_kin_relationship",
                    models.CharField(blank=True, max_length=100),
                ),
                ("next_of_kin_phone", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["employee_id"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("JUNIOR", "Junior"),
                            ("SENIOR", "Senior"),
                            ("MANAGEMENT", "Management"),
                            ("EXECUTIVE", "Executive"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Employee Categories",
            },
        ),
        migrations.CreateModel(
            name="EmploymentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("DIRECT", "Direct Employee"),
                            ("CONTRACTOR", "Contractor"),
                            ("CONSULTANT", "Consultant"),
                            ("TEMPORARY", "Temporary"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Employment Types",
            },
        ),
        migrations.CreateModel(
            name="TerminationReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("RESIGNATION", "Resignation"),
                            ("REDUNDANCY", "Redundancy"),
                            ("RETIREMENT", "Retirement"),
                            ("TERMINATED", "Terminated"),
                            ("ENDED", "Contract Ended"),
                            ("DECEASED", "Deceased"),
                            ("OTHER", "Other"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Termination Reasons",
            },
        ),
        migrations.CreateModel(
            name="Termination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("termination_date", models.DateField()),
                (
                    "payroll_final",
                    models.BooleanField(
                        default=False, help_text="Final payroll processed"
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="termination",
                        to="hcm.employee",
                    ),
                ),
                (
                    "termination_reason",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hcm.terminationreason",
                    ),
                ),
            ],
            options={
                "ordering": ["-termination_date"],
            },
        ),
        migrations.CreateModel(
            name="Engagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engagement_date", models.DateField()),
                (
                    "contract_duration_months",
                    models.IntegerField(blank=True, null=True),
                ),
                ("initial_contract_end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hcm.contracttype",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement",
                        to="hcm.employee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Junior/Senior/Management",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hcm.employeecategory",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="contractor_company",
            field=models.ForeignKey(
                blank=True,
                help_text="Contractor firm this person works for (if external contractor)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deployed_contractors",
                to="core.workspace",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hcm.department",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="employment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="hcm.employmenttype"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization/company this employee belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="core.workspace",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_departments",
                to="hcm.employee",
            ),
        ),
        migrations.CreateModel(
            name="ContractorCompliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_permit_valid", models.BooleanField(default=False)),
                ("work_permit_number", models.CharField(blank=True, max_length=100)),
                ("work_permit_expiry", models.DateField(blank=True, null=True)),
                ("safety_induction_completed", models.BooleanField(default=False)),
                ("safety_induction_date", models.DateField(blank=True, null=True)),
                (
                    "safety_induction_valid_until",
                    models.DateField(blank=True, null=True),
                ),
                ("medical_clearance_valid", models.BooleanField(default=False)),
                ("medical_clearance_date", models.DateField(blank=True, null=True)),
                ("medical_clearance_expiry", models.DateField(blank=True, null=True)),
                ("insurance_valid", models.BooleanField(default=False)),
                ("insurance_provider", models.CharField(blank=True, max_length=200)),
                (
                    "insurance_policy_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                ("police_clearance_valid", models.BooleanField(default=False)),
                ("police_clearance_date", models.DateField(blank=True, null=True)),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("COMPLIANT", "Compliant"),
                            ("EXPIRING_SOON", "Expiring Soon"),
                            ("NON_COMPLIANT", "Non-Compliant"),
                            ("PENDING_REVIEW", "Pending Review"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional compliance notes"
                    ),
                ),
                ("last_checked", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client_workspace",
                    models.ForeignKey(
                        help_text="Client site where contractor is deployed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contractor_compliance",
                        to="core.workspace",
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        limit_choices_to={"contractor_type": "CONTRACTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_records",
                        to="hcm.employee",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contractor Compliance Records",
                "ordering": ["-last_checked"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_number", models.CharField(max_length=100, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("duration_months", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("RENEWED", "Renewed"),
                            ("TERMINATED", "Terminated"),
                            ("PENDING_RENEWAL", "Pending Renewal"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("salary_currency", models.CharField(default="ZMW", max_length=3)),
                (
                    "basic_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "document_url",
                    models.URLField(blank=True, help_text="Link to contract document"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hcm.contracttype",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="hcm.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["employment_status", "hire_date"],
                name="hcm_employe_employm_111d1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["department", "employment_status"],
                name="hcm_employe_departm_5a4fa2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contractorcompliance",
            unique_together={("contractor", "client_workspace")},
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["employee", "status"], name="hcm_contrac_employe_8548d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["end_date"], name="hcm_contrac_end_dat_b76b59_idx"
            ),
        ),
    ]
