# Generated by Django 4.2.8 on 2026-01-25 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hcm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Local"),
                            ("REGIONAL", "Regional"),
                            ("NATIONAL", "National"),
                            ("EXPATRIATE", "Expatriate"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Employee Classifications",
            },
        ),
        migrations.AlterField(
            model_name="contracttype",
            name="name",
            field=models.CharField(
                choices=[
                    ("PERMANENT", "Permanent"),
                    ("FIXED_TERM", "Fixed-Term"),
                    ("PROBATION", "Probation"),
                    ("SHORT_TERM", "Short-Term"),
                    ("VERBAL", "Verbal Agreement"),
                    ("TEMPORARY", "Temporary"),
                    ("SEASONAL", "Seasonal"),
                    ("CONSULTANT", "Consultant"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="classification",
            field=models.ForeignKey(
                blank=True,
                help_text="Local/Regional/National/Expatriate",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hcm.employeeclassification",
            ),
        ),
    ]
