# Generated by Django 4.2.8 on 2026-02-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hcm", "0004_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="tpin",
            field=models.CharField(
                blank=True, help_text="Tax PIN", max_length=50, null=True, unique=True
            ),
        ),
    ]
