# Generated by Django 4.2.8 on 2026-03-03 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_workspace'),
        ('hcm', '0005_alter_employee_tpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Organization/workspace this department belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hcm.department'),
        ),
    ]
