# Generated by Django 4.2.8 on 2026-06-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcm', '0009_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contract',
            name='hcm_contract_emp_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='contract',
            name='hcm_contract_end_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='hcm_emp_workspace_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='hcm_emp_ws_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='hcm_emp_created_idx',
        ),
    ]
