# Generated by Django 4.2.8 on 2026-07-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcm', '0011_employee_email_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Account holder name', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Account number', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_branch',
            field=models.CharField(blank=True, help_text='Branch name or code', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Name of the bank', max_length=100),
        ),
    ]
