# Generated by Django 4.2.8 on 2026-01-01 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("hcm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="hcm.employee",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="core.site",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workspacemembership",
            unique_together={("user", "workspace")},
        ),
        migrations.AlterUniqueTogether(
            name="site",
            unique_together={("workspace", "name"), ("workspace", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("workspace", "name"), ("workspace", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("workspace", "name"), ("workspace", "code")},
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["employee", "status"], name="core_assign_employe_7e439d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["site", "client"], name="core_assign_site_id_8d1942_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["assignment_end_date"], name="core_assign_assignm_d30498_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignment",
            unique_together={("employee", "site", "client", "assignment_start_date")},
        ),
    ]
