# Generated by Django 4.2.8 on 2026-01-15 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="blue", help_text="For UI display", max_length=20
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_roles",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("workspace", "name")},
            },
        ),
        migrations.CreateModel(
            name="CustomRolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_code",
                    models.CharField(
                        choices=[
                            ("can_manage_members", "Manage Workspace Members"),
                            ("can_manage_settings", "Manage Workspace Settings"),
                            ("can_view_employees", "View Employees"),
                            ("can_create_employees", "Create Employees"),
                            ("can_edit_employees", "Edit Employees"),
                            ("can_delete_employees", "Delete Employees"),
                            ("can_manage_sites", "Manage Sites"),
                            ("can_manage_projects", "Manage Projects"),
                            ("can_manage_clients", "Manage Clients"),
                            ("can_manage_assignments", "Manage Assignments"),
                            ("can_view_payroll", "View Payroll"),
                            ("can_manage_payroll", "Manage Payroll"),
                            ("can_approve_leaves", "Approve Leaves"),
                            ("can_approve_timesheets", "Approve Timesheets"),
                            ("can_manage_contracts", "Manage Contracts"),
                            ("can_view_reports", "View Reports"),
                            ("can_create_reports", "Create Reports"),
                            ("can_view_analytics", "View Analytics"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="core.customrole",
                    ),
                ),
            ],
            options={
                "unique_together": {("role", "permission_code")},
            },
        ),
    ]
