# Generated by Django 4.2.8 on 2026-01-31 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_usercustomrole"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="client",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="client",
            name="workspace",
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="project",
            name="site",
        ),
        migrations.RemoveField(
            model_name="project",
            name="workspace",
        ),
        migrations.AlterUniqueTogether(
            name="site",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="site",
            name="workspace",
        ),
        migrations.DeleteModel(
            name="Assignment",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="Site",
        ),
    ]
