# Generated by Django 4.2.8 on 2026-02-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hcm", "0003_employeedocument"),
        ("core", "0006_alter_client_unique_together_remove_client_workspace_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=300)),
                ("address", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization that owns this site",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sites",
                "unique_together": {("workspace", "code"), ("workspace", "name")},
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning"),
                            ("ACTIVE", "Active"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="ACTIVE",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="core.site",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization that owns this project",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Projects",
                "unique_together": {("workspace", "code"), ("workspace", "name")},
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50)),
                ("industry", models.CharField(blank=True, max_length=200)),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization managing this client relationship",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Clients",
                "unique_together": {("workspace", "code"), ("workspace", "name")},
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("ENDED", "Ended"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("assignment_start_date", models.DateField()),
                ("assignment_end_date", models.DateField(blank=True, null=True)),
                (
                    "role_at_site",
                    models.CharField(
                        blank=True,
                        help_text="Role specific to this assignment",
                        max_length=200,
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Day, Night, Rotating",
                        max_length=50,
                    ),
                ),
                (
                    "visible_to_client",
                    models.BooleanField(
                        default=True, help_text="Can client see this assignment?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client paying for/receiving contractor",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.client",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="hcm.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="core.project",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-assignment_start_date"],
                "indexes": [
                    models.Index(
                        fields=["employee", "status"],
                        name="core_assign_employe_7e439d_idx",
                    ),
                    models.Index(
                        fields=["site", "client"], name="core_assign_site_id_8d1942_idx"
                    ),
                    models.Index(
                        fields=["assignment_end_date"],
                        name="core_assign_assignm_d30498_idx",
                    ),
                ],
                "unique_together": {
                    ("employee", "site", "client", "assignment_start_date")
                },
            },
        ),
    ]
