# Generated by Django 4.2.8 on 2026-02-08 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_site_project_client_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="core.site",
            ),
        ),
    ]
