# Generated by Django 4.2.8 on 2026-02-21 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_workspace_logo"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="project",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="project",
            name="code",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="project",
            name="site",
        ),
        migrations.RemoveField(
            model_name="project",
            name="workspace",
        ),
    ]
