# Generated by Django 4.2.8 on 2026-02-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_project_unique_together_remove_project_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="progress",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="team_members",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
