# Generated by Django 4.2.8 on 2026-03-03 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_project_progress_project_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Organization/workspace this project belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.workspace'),
        ),
    ]
