# Generated by Django 4.2.8 on 2026-01-31 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hcm", "0002_employeeclassification_alter_contracttype_name_and_more"),
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoubleTicketRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_date",
                    models.DateField(help_text="Sunday or public holiday worked"),
                ),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Hours worked (default 8 for full shift)",
                        max_digits=4,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Reason for Sunday/holiday work"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PAID", "Paid"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "calculated_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculated double ticket payment",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_double_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="double_tickets",
                        to="hcm.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Double Ticket Request",
                "verbose_name_plural": "Double Ticket Requests",
                "ordering": ["-work_date", "-created_at"],
            },
        ),
    ]
