# Generated by Django 4.2.8 on 2026-06-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='absenteeism',
            name='leave_absent_emp_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='doubleticketrequest',
            name='leave_dt_emp_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='leave_req_emp_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='leave_req_dates_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='leave_req_type_status_idx',
        ),
    ]
