import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// Extend jsPDF type to include autoTable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: typeof autoTable;
  }
}

export const exportReportToPDF = (report: any) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.text('Activity Report', 14, 20);
  
  // Report details
  doc.setFontSize(12);
  doc.text(`Report Number: ${report.report_number || 'N/A'}`, 14, 35);
  doc.text(`Title: ${report.title || 'N/A'}`, 14, 45);
  doc.text(`Report Type: ${report.report_type || 'N/A'}`, 14, 55);
  doc.text(`Severity: ${report.severity || 'N/A'}`, 14, 65);
  doc.text(`Created: ${report.created_at ? new Date(report.created_at).toLocaleDateString() : 'N/A'}`, 14, 75);
  
  // Description
  if (report.description) {
    doc.setFontSize(14);
    doc.text('Description:', 14, 90);
    doc.setFontSize(11);
    const splitDescription = doc.splitTextToSize(report.description, 180);
    doc.text(splitDescription, 14, 100);
  }
  
  // Footer
  doc.setFontSize(8);
  doc.text('Generated by YARA HRMS', 14, doc.internal.pageSize.height - 10);
  
  doc.save(`Report_${report.report_number || 'export'}.pdf`);
};

export const exportInvestigationToPDF = (investigation: any) => {
  const doc = new jsPDF();
  
  doc.setFontSize(20);
  doc.text('Investigation Report', 14, 20);
  
  doc.setFontSize(12);
  doc.text(`Investigation #: ${investigation.investigation_number || 'N/A'}`, 14, 35);
  doc.text(`Title: ${investigation.title || 'N/A'}`, 14, 45);
  doc.text(`Investigator: ${investigation.investigator || 'N/A'}`, 14, 55);
  doc.text(`Status: ${investigation.status || 'N/A'}`, 14, 65);
  doc.text(`Date: ${investigation.investigation_date ? new Date(investigation.investigation_date).toLocaleDateString() : 'N/A'}`, 14, 75);
  
  let yPos = 90;
  
  if (investigation.description) {
    doc.setFontSize(14);
    doc.text('Description:', 14, yPos);
    doc.setFontSize(11);
    const splitText = doc.splitTextToSize(investigation.description, 180);
    doc.text(splitText, 14, yPos + 10);
    yPos += 10 + (splitText.length * 7);
  }
  
  if (investigation.findings) {
    doc.setFontSize(14);
    doc.text('Findings:', 14, yPos + 10);
    doc.setFontSize(11);
    const splitText = doc.splitTextToSize(investigation.findings, 180);
    doc.text(splitText, 14, yPos + 20);
    yPos += 20 + (splitText.length * 7);
  }
  
  if (investigation.observations) {
    doc.setFontSize(14);
    doc.text('Observations:', 14, yPos + 10);
    doc.setFontSize(11);
    const splitText = doc.splitTextToSize(investigation.observations, 180);
    doc.text(splitText, 14, yPos + 20);
    yPos += 20 + (splitText.length * 7);
  }
  
  if (investigation.conclusion_of_scene) {
    doc.setFontSize(14);
    doc.text('Conclusion:', 14, yPos + 10);
    doc.setFontSize(11);
    const splitText = doc.splitTextToSize(investigation.conclusion_of_scene, 180);
    doc.text(splitText, 14, yPos + 20);
  }
  
  doc.setFontSize(8);
  doc.text('Generated by YARA HRMS', 14, doc.internal.pageSize.height - 10);
  
  doc.save(`Investigation_${investigation.investigation_number || 'export'}.pdf`);
};

export const exportHearingToPDF = (hearing: any) => {
  const doc = new jsPDF();
  
  doc.setFontSize(20);
  doc.text('Hearing Report', 14, 20);
  
  doc.setFontSize(12);
  doc.text(`Hearing #: ${hearing.hearing_number || 'N/A'}`, 14, 35);
  doc.text(`Employee: ${hearing.employee_name || 'N/A'}`, 14, 45);
  doc.text(`Date: ${hearing.hearing_date ? new Date(hearing.hearing_date).toLocaleDateString() : 'N/A'}`, 14, 55);
  doc.text(`Type: ${hearing.hearing_type || 'N/A'}`, 14, 65);
  doc.text(`Status: ${hearing.status || 'N/A'}`, 14, 75);
  doc.text(`Presiding Officer: ${hearing.presiding_officer || 'N/A'}`, 14, 85);
  doc.text(`Outcome: ${hearing.outcome || 'N/A'}`, 14, 95);
  
  if (hearing.notes) {
    doc.setFontSize(14);
    doc.text('Notes:', 14, 110);
    doc.setFontSize(11);
    const splitText = doc.splitTextToSize(hearing.notes, 180);
    doc.text(splitText, 14, 120);
  }
  
  doc.setFontSize(8);
  doc.text('Generated by YARA HRMS', 14, doc.internal.pageSize.height - 10);
  
  doc.save(`Hearing_${hearing.hearing_number || 'export'}.pdf`);
};

export const exportChargeToPDF = (charge: any) => {
  const doc = new jsPDF();
  
  doc.setFontSize(20);
  doc.text('Charge Sheet', 14, 20);
  
  doc.setFontSize(12);
  doc.text(`Charge #: ${charge.charge_number || 'N/A'}`, 14, 35);
  doc.text(`Employee: ${charge.employee_name || 'N/A'}`, 14, 45);
  doc.text(`Severity: ${charge.severity || 'N/A'}`, 14, 55);
  doc.text(`Status: ${charge.status || 'N/A'}`, 14, 65);
  doc.text(`Filed Date: ${charge.filed_date ? new Date(charge.filed_date).toLocaleDateString() : 'N/A'}`, 14, 75);
  
  if (charge.charge_description) {
    doc.setFontSize(14);
    doc.text('Description:', 14, 90);
    doc.setFontSize(11);
    const splitText = doc.splitTextToSize(charge.charge_description, 180);
    doc.text(splitText, 14, 100);
  }
  
  doc.setFontSize(8);
  doc.text('Generated by YARA HRMS', 14, doc.internal.pageSize.height - 10);
  
  doc.save(`Charge_${charge.charge_number || 'export'}.pdf`);
};

export const exportCaseStudyToPDF = (caseStudy: any) => {
  const doc = new jsPDF();
  
  doc.setFontSize(20);
  doc.text('Case Study', 14, 20);
  
  doc.setFontSize(12);
  doc.text(`Case #: ${caseStudy.case_number || 'N/A'}`, 14, 35);
  doc.text(`Status: ${caseStudy.status || 'N/A'}`, 14, 45);
  doc.text(`Verdict: ${caseStudy.verdict || 'N/A'}`, 14, 55);
  doc.text(`Created: ${caseStudy.created_at ? new Date(caseStudy.created_at).toLocaleDateString() : 'N/A'}`, 14, 65);

  let yPos = 80;

  const addSection = (label: string, value?: string) => {
    if (!value) return;
    doc.setFontSize(14);
    doc.text(`${label}:`, 14, yPos);
    doc.setFontSize(11);
    const splitText = doc.splitTextToSize(value, 180);
    doc.text(splitText, 14, yPos + 10);
    yPos += 10 + (splitText.length * 7);
  };

  addSection('Charges', caseStudy.charges_text || '');
  addSection('Allegations', caseStudy.allegations || '');
  addSection('Plea', caseStudy.plea || '');
  addSection('Statement', caseStudy.statement || '');
  addSection('Sanctions', caseStudy.sanctions_imposed || '');
  addSection('Final Verdict Notes', caseStudy.final_verdict_text || '');
  
  doc.setFontSize(8);
  doc.text('Generated by YARA HRMS', 14, doc.internal.pageSize.height - 10);
  
  doc.save(`CaseStudy_${caseStudy.case_number || 'export'}.pdf`);
};

export const exportAtrToPDF = (atr: any) => {
  const doc = new jsPDF();

  doc.setFontSize(20);
  doc.text('Approval To Recruit (ATR)', 14, 20);

  doc.setFontSize(12);
  doc.text(`Department: ${atr.department || 'N/A'}`, 14, 35);
  doc.text(`Role: ${atr.role || 'N/A'}`, 14, 45);
  doc.text(`Hiring Manager: ${atr.hiringManager || 'N/A'}`, 14, 55);
  doc.text(`Requested Date: ${atr.requestedDate || 'N/A'}`, 14, 65);
  doc.text(`Vacancies: ${atr.vacancies ?? 'N/A'}`, 14, 75);
  doc.text(`Status: ${atr.status ? String(atr.status).toUpperCase() : 'N/A'}`, 14, 85);

  if (atr.reason) {
    doc.setFontSize(14);
    doc.text('Reason:', 14, 100);
    doc.setFontSize(11);
    const splitText = doc.splitTextToSize(atr.reason, 180);
    doc.text(splitText, 14, 110);
  }

  doc.setFontSize(8);
  doc.text('Generated by YARA HRMS', 14, doc.internal.pageSize.height - 10);

  doc.save(`ATR_${atr.id || 'export'}.pdf`);
};

export const exportCandidateToPDF = (candidate: any) => {
  const doc = new jsPDF();

  doc.setFontSize(20);
  doc.text('Recruitment Candidate', 14, 20);

  doc.setFontSize(12);
  doc.text(`Name: ${candidate.name || 'N/A'}`, 14, 35);
  doc.text(`Position: ${candidate.position || 'N/A'}`, 14, 45);
  doc.text(`Status: ${candidate.status || 'N/A'}`, 14, 55);
  doc.text(`Engaged Date: ${candidate.engaged_date || 'N/A'}`, 14, 65);
  doc.text(`Interview Due: ${candidate.interview_due_date || 'N/A'}`, 14, 75);
  doc.text(`Phone: ${candidate.phone_number || 'N/A'}`, 14, 85);
  doc.text(`NRC: ${candidate.nrc || 'N/A'}`, 14, 95);

  if (candidate.accommodation) {
    doc.setFontSize(12);
    doc.text(`Accommodation: ${candidate.accommodation}`, 14, 105);
  }

  doc.setFontSize(8);
  doc.text('Generated by YARA HRMS', 14, doc.internal.pageSize.height - 10);

  doc.save(`Candidate_${candidate.id || 'export'}.pdf`);
};

// Export table data to PDF with auto table
export const exportTableToPDF = (
  title: string,
  columns: string[],
  data: any[][],
  filename: string
) => {
  const doc = new jsPDF();
  
  doc.setFontSize(18);
  doc.text(title, 14, 15);
  
  autoTable(doc, {
    head: [columns],
    body: data,
    startY: 25,
    theme: 'grid',
    styles: { fontSize: 10 },
    headStyles: { fillColor: [212, 175, 55] },
  });
  
  doc.setFontSize(8);
  doc.text('Generated by YARA HRMS', 14, doc.internal.pageSize.height - 10);
  
  doc.save(filename);
};
