# Generated by Django 4.2.8 on 2026-01-01 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hcm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("SILICOSIS", "Silicosis"),
                            ("PHYSICAL", "Physical Examination"),
                            ("BASELINE", "Baseline Medical"),
                            ("EXIT", "Exit Medical"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "frequency_months",
                    models.IntegerField(
                        blank=True,
                        help_text="Frequency in months for mandatory re-tests",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Medical Types",
            },
        ),
        migrations.CreateModel(
            name="PermitType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("SITE", "Site Permit"),
                            ("PIT", "Pit Entry"),
                            ("IBF", "IBF"),
                            ("INITIAL", "Initial Entry"),
                            ("LEO", "LEO Induction"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("validity_months", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Permit Types",
            },
        ),
        migrations.CreateModel(
            name="TrainingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ADMINISTRATIVE", "Administrative"),
                            ("THIRD_PARTY", "Third-Party Certified"),
                            ("DRILL", "Drill"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("requires_certification", models.BooleanField(default=False)),
                ("default_validity_months", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Training Types",
            },
        ),
        migrations.CreateModel(
            name="Probation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("EXTENDED", "Extended"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("decision_date", models.DateField(blank=True, null=True)),
                ("decision_remarks", models.TextField(blank=True)),
                ("decided_by", models.CharField(blank=True, max_length=200)),
                ("extension_end_date", models.DateField(blank=True, null=True)),
                ("extension_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="probation",
                        to="hcm.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("certificate_number", models.CharField(blank=True, max_length=100)),
                (
                    "certificate_document",
                    models.FileField(blank=True, upload_to="training_certs/"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainings",
                        to="hcm.employee",
                    ),
                ),
                (
                    "training_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tracking.trainingtype",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
                "indexes": [
                    models.Index(
                        fields=["employee", "status"],
                        name="tracking_tr_employe_637af2_idx",
                    ),
                    models.Index(
                        fields=["expiry_date"], name="tracking_tr_expiry__8ff2b5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Permit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ISSUED", "Issued"),
                            ("EXPIRED", "Expired"),
                            ("RENEWED", "Renewed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("permit_number", models.CharField(blank=True, max_length=100)),
                ("document", models.FileField(blank=True, upload_to="permits/")),
                ("issued_by", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permits",
                        to="hcm.employee",
                    ),
                ),
                (
                    "permit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tracking.permittype",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
                "indexes": [
                    models.Index(
                        fields=["employee", "permit_type"],
                        name="tracking_pe_employe_d090d8_idx",
                    ),
                    models.Index(
                        fields=["expiry_date"], name="tracking_pe_expiry__10cd7f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Medical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("facility", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("CLEARED", "Cleared"),
                            ("RESTRICTED", "Restricted"),
                            ("NOT_CLEARED", "Not Cleared"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("clearance_status", models.CharField(blank=True, max_length=50)),
                ("findings", models.TextField(blank=True)),
                (
                    "restrictions",
                    models.TextField(blank=True, help_text="Any work restrictions"),
                ),
                (
                    "report_document",
                    models.FileField(blank=True, upload_to="medical_reports/"),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicals",
                        to="hcm.employee",
                    ),
                ),
                (
                    "medical_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tracking.medicaltype",
                    ),
                ),
            ],
            options={
                "ordering": ["-completion_date"],
                "indexes": [
                    models.Index(
                        fields=["employee", "medical_type"],
                        name="tracking_me_employe_0a6636_idx",
                    ),
                    models.Index(
                        fields=["expiry_date"], name="tracking_me_expiry__71a2fb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplianceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("TRAINING", "Training Expiry"),
                            ("MEDICAL", "Medical Expiry"),
                            ("PERMIT", "Permit Expiry"),
                            ("CONTRACT", "Contract Expiry"),
                            ("PROBATION", "Probation Due"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("due_date", models.DateField()),
                ("content_type", models.CharField(blank=True, max_length=50)),
                ("object_id", models.IntegerField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_by", models.CharField(blank=True, max_length=200)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_alerts",
                        to="hcm.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
                "indexes": [
                    models.Index(
                        fields=["employee", "status"],
                        name="tracking_co_employe_41f7bb_idx",
                    ),
                    models.Index(
                        fields=["due_date"], name="tracking_co_due_dat_f9a601_idx"
                    ),
                ],
            },
        ),
    ]
