# Generated by Django 4.2.8 on 2026-02-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="medical",
            new_name="tracking_me_employe_95b7a0_idx",
            old_name="tracking_me_employe_0a6636_idx",
        ),
        migrations.AlterField(
            model_name="medical",
            name="medical_type",
            field=models.CharField(
                help_text="Type of medical examination (e.g., Silicosis, Physical Examination)",
                max_length=100,
            ),
        ),
    ]
