# Generated by Django 4.2.8 on 2026-06-09 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_workspace_logo_data'),
        ('tracking', '0002_rename_tracking_me_employe_0a6636_idx_tracking_me_employe_95b7a0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltype',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_types', to='core.workspace'),
        ),
        migrations.AddField(
            model_name='trainingtype',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_types', to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='medicaltype',
            name='name',
            field=models.CharField(choices=[('SILICOSIS', 'Silicosis'), ('PHYSICAL', 'Physical Examination'), ('BASELINE', 'Baseline Medical'), ('EXIT', 'Exit Medical')], max_length=100),
        ),
        migrations.AlterField(
            model_name='trainingtype',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='medicaltype',
            unique_together={('workspace', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='trainingtype',
            unique_together={('workspace', 'name')},
        ),
    ]
