# Generated by Django 4.2.8 on 2026-01-01 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hcm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50, unique=True)),
                ("currency", models.CharField(default="ZMW", max_length=3)),
                (
                    "min_gross",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_gross",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("employee_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="TitleBreakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(db_index=True, max_length=200)),
                ("currency", models.CharField(default="ZMW", max_length=3)),
                (
                    "basic",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "housing",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "transportation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "lunch",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gross",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("position", "currency")},
            },
        ),
        migrations.CreateModel(
            name="PayrollEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_hire", models.DateField()),
                ("department", models.CharField(max_length=200)),
                ("resident", models.CharField(max_length=200)),
                ("currency", models.CharField(default="ZMW", max_length=3)),
                (
                    "basic",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "housing",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "transportation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "lunch",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gross",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_entries",
                        to="hcm.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["employee__employee_id"],
            },
        ),
        migrations.CreateModel(
            name="PayrollComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(db_index=True, max_length=200)),
                ("currency", models.CharField(default="ZMW", max_length=3)),
                (
                    "basic",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "housing",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "transportation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "lunch",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gross",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("position", "currency")},
            },
        ),
    ]
