# Generated by Django 4.2.8 on 2026-01-15 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hcm", "0001_initial"),
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("PAID", "Paid"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-year", "-month"],
                "unique_together": {("year", "month")},
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "housing_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "transportation_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "lunch_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "unpaid_leave_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Days of unpaid leave",
                        max_digits=5,
                    ),
                ),
                (
                    "unpaid_leave_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "absenteeism_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Days absent",
                        max_digits=5,
                    ),
                ),
                (
                    "absenteeism_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("gross_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "napsa_employee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "napsa_employer",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "paye_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "nhima_employee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "nhima_employer",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_custom_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("net_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_processed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="hcm.employee",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="payroll.payrollperiod",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-period__year",
                    "-period__month",
                    "employee__employee_id",
                ],
                "unique_together": {("employee", "period")},
            },
        ),
        migrations.CreateModel(
            name="PayslipDeduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="e.g., 'Loan Repayment', 'Advance Recovery'",
                        max_length=200,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payslip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_deductions",
                        to="payroll.payslip",
                    ),
                ),
            ],
            options={
                "ordering": ["description"],
            },
        ),
    ]
