# Generated by Django 4.2.8 on 2026-01-17 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_usercustomrole"),
        ("payroll", "0002_payrollperiod_payslip_payslipdeduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="bonus",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Bonus payment - fully taxable emolument, included in gross earnings",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="overtime_payment",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Overtime pay - fully taxable emolument, included in gross earnings",
                max_digits=12,
            ),
        ),
        migrations.CreateModel(
            name="WorkspaceStatutorySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "napsa_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.05,
                        help_text="NAPSA employee contribution rate (default 5%)",
                        max_digits=5,
                    ),
                ),
                (
                    "napsa_ceiling_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        default=34164.0,
                        help_text="Monthly NAPSA ceiling (default K34,164.00)",
                        max_digits=12,
                    ),
                ),
                (
                    "nhima_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.01,
                        help_text="NHIMA employee contribution rate (default 1%)",
                        max_digits=5,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        auto_now=True, help_text="Date these settings became effective"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statutory_settings",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Workspace Statutory Settings",
            },
        ),
        migrations.CreateModel(
            name="PayeTaxBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum chargeable income for this band",
                        max_digits=12,
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum chargeable income for this band (use high number for open-ended)",
                        max_digits=12,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Tax rate for this band (e.g., 0.20 for 20%)",
                        max_digits=5,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which bands are applied (0=first)",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        auto_now=True, help_text="Date this band became effective"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paye_tax_bands",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PAYE Tax Bands",
                "ordering": ["workspace", "order", "min_amount"],
                "unique_together": {("workspace", "min_amount", "max_amount")},
            },
        ),
    ]
