# Generated by Django 4.2.8 on 2026-01-18 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payroll", "0003_payslip_bonus_payslip_overtime_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="version",
            field=models.PositiveIntegerField(
                default=1, help_text="Incremented when payslip is recalculated"
            ),
        ),
        migrations.CreateModel(
            name="PayslipAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("CALCULATED", "Calculated"),
                            ("UPDATED", "Updated"),
                            ("DELETED", "Deleted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Delta changes for UPDATED actions or calculation details",
                    ),
                ),
                (
                    "payslip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="payroll.payslip",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Payslip Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
