# Generated by Django 4.2.8 on 2026-01-18 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hcm", "0001_initial"),
        ("payroll", "0004_payslip_version_payslipauditlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payslip",
            options={
                "ordering": [
                    "-period__year",
                    "-period__month",
                    "employee__employee_id",
                    "-version",
                ]
            },
        ),
        migrations.AlterUniqueTogether(
            name="payslip",
            unique_together={("employee", "period", "version")},
        ),
        migrations.AddField(
            model_name="payslip",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Only the latest version is active"
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="original_payslip",
            field=models.ForeignKey(
                blank=True,
                help_text="Links to the first version of this payslip",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="payroll.payslip",
            ),
        ),
    ]
