# Generated by Django 4.2.8 on 2026-02-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "payroll",
            "0005_alter_payslip_options_alter_payslip_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payrollentry",
            name="date_of_hire",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payrollentry",
            name="department",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="payrollentry",
            name="resident",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
