# Generated by Django 4.2.8 on 2026-02-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0006_alter_payrollentry_date_of_hire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payrollcomponent",
            name="basic",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payrollcomponent",
            name="gross",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payrollcomponent",
            name="housing",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payrollcomponent",
            name="lunch",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payrollcomponent",
            name="net",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payrollcomponent",
            name="transportation",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payrollentry",
            name="basic",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payrollentry",
            name="gross",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payrollentry",
            name="housing",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payrollentry",
            name="lunch",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payrollentry",
            name="net",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payrollentry",
            name="transportation",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="absenteeism_deduction",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="basic_salary",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="bonus",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Bonus payment - fully taxable emolument, included in gross earnings",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="gross_salary",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="housing_allowance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="lunch_allowance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="napsa_employee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="napsa_employer",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="net_salary",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="nhima_employee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="nhima_employer",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="other_allowances",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="overtime_payment",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Overtime pay - fully taxable emolument, included in gross earnings",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="paye_tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="total_custom_deductions",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="total_deductions",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="transportation_allowance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="unpaid_leave_deduction",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="salaryrange",
            name="max_gross",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="salaryrange",
            name="min_gross",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="titlebreakdown",
            name="basic",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="titlebreakdown",
            name="gross",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="titlebreakdown",
            name="housing",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="titlebreakdown",
            name="lunch",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="titlebreakdown",
            name="net",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="titlebreakdown",
            name="transportation",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
