# Generated by Django 4.2.8 on 2026-02-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0007_alter_payrollcomponent_basic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="double_ticket_payment",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Double ticket payment for Sunday/Holiday work - fully taxable emolument",
                max_digits=15,
            ),
        ),
    ]
