# Generated by Django 4.2.8 on 2026-05-06 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_workspace_logo_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0009_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAYEReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_employees', models.PositiveIntegerField(default=0)),
                ('total_gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_chargeable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_tax_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_tax_payable', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Return submission status', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submission_notes', models.TextField(blank=True, help_text='Notes about submission or rejection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'PAYE Returns',
                'ordering': ['-period__year', '-period__month'],
            },
        ),
        migrations.RemoveIndex(
            model_name='payrollentry',
            name='payroll_entry_emp_idx',
        ),
        migrations.RemoveIndex(
            model_name='payrollentry',
            name='payroll_entry_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='payslip',
            name='payroll_slip_emp_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='payslip',
            name='payroll_slip_period_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='payslip',
            name='payroll_slip_active_created_idx',
        ),
        migrations.AddField(
            model_name='payereturn',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payereturn',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paye_returns', to='payroll.payrollperiod'),
        ),
        migrations.AddField(
            model_name='payereturn',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paye_returns', to='core.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='payereturn',
            unique_together={('workspace', 'period')},
        ),
    ]
