# Generated by Django 4.2.8 on 2026-06-09 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_workspace_logo_data'),
        ('payroll', '0010_payereturn_remove_payrollentry_payroll_entry_emp_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacestatutorysettings',
            name='basic_ratio',
            field=models.DecimalField(decimal_places=4, default=0.45, help_text='Fraction of gross allocated to basic salary (default 45%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='workspacestatutorysettings',
            name='housing_ratio',
            field=models.DecimalField(decimal_places=4, default=0.25, help_text='Fraction of gross allocated to housing allowance (default 25%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='workspacestatutorysettings',
            name='lunch_ratio',
            field=models.DecimalField(decimal_places=4, default=0.15, help_text='Fraction of gross allocated to lunch allowance (default 15%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='workspacestatutorysettings',
            name='transport_ratio',
            field=models.DecimalField(decimal_places=4, default=0.15, help_text='Fraction of gross allocated to transportation allowance (default 15%)', max_digits=5),
        ),
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('NAPSA', 'NAPSA Compliance Certificate'), ('NHIMA', 'NHIMA Registration Certificate'), ('ZRA_TPIN', 'ZRA TPIN Certificate'), ('ZRA_TCC', 'Tax Clearance Certificate (TCC)'), ('WCFCB', 'Workers Compensation Certificate (WCFCB)'), ('PACRA', 'PACRA Certificate / Annual Returns'), ('MOL', 'Ministry of Labour Registration'), ('OHS', 'OHS Compliance Record'), ('SDL', 'Skills Development Levy (SDL)'), ('OTHER', 'Other')], max_length=20)),
                ('document_name', models.CharField(blank=True, help_text='Custom display name (leave blank to use document type label)', max_length=200)),
                ('reference_number', models.CharField(blank=True, help_text='Certificate/reference number', max_length=100)),
                ('issued_by', models.CharField(blank=True, help_text='Issuing authority name', max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Leave blank for permanent documents', null=True)),
                ('is_permanent', models.BooleanField(default=False, help_text='Tick for once-off documents with no expiry (TPIN, MOL registration)')),
                ('document_file', models.FileField(blank=True, help_text='Attach scanned certificate', null=True, upload_to='compliance_docs/%Y/')),
                ('notes', models.TextField(blank=True)),
                ('reminder_days', models.PositiveIntegerField(default=30, help_text='Alert X days before expiry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_documents', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Compliance Document',
                'verbose_name_plural': 'Compliance Documents',
                'ordering': ['document_type', '-issue_date'],
            },
        ),
    ]
