# Generated by Django 4.2.8 on 2026-01-01 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appraisal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_held", models.CharField(max_length=200)),
                ("review_start", models.DateField()),
                ("review_end", models.DateField()),
                (
                    "feedback_notes",
                    models.TextField(
                        blank=True, help_text="180°/360° feedback summary"
                    ),
                ),
                ("employee_comments", models.TextField(blank=True)),
                ("supervisor_comments", models.TextField(blank=True)),
                ("employee_signed_at", models.DateTimeField(blank=True, null=True)),
                ("supervisor_signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "overall_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "PP"), (2, "SP"), (3, "AP"), (4, "AE"), (5, "OP")],
                        null=True,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="appraisals/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-review_end"],
            },
        ),
        migrations.CreateModel(
            name="AppraisalDevelopmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("training_need", models.TextField()),
                ("action", models.TextField(blank=True)),
                ("responsible", models.CharField(blank=True, max_length=200)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "application_note",
                    models.TextField(
                        blank=True, help_text="How learning will be applied"
                    ),
                ),
                ("review_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AppraisalFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("PERFORMANCE", "Performance Factors"),
                            ("BEHAVIORAL", "Behavioral Traits"),
                            ("SUPERVISORY", "Supervisory Factors"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "PP"), (2, "SP"), (3, "AP"), (4, "AE"), (5, "OP")],
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="AppraisalImprovementItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue",
                    models.TextField(
                        help_text="Objectives not achieved / challenges / areas for improvement"
                    ),
                ),
                ("limiting_factors", models.TextField(blank=True)),
                ("actions", models.TextField(blank=True)),
                ("completion_indicator", models.TextField(blank=True)),
                ("due_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AppraisalNextObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_area", models.CharField(blank=True, max_length=200)),
                (
                    "objective",
                    models.TextField(help_text="SMART objective for next period"),
                ),
                (
                    "indicators",
                    models.TextField(
                        blank=True, help_text="How achievement will be measured"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppraisalObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(help_text="State Performance Objective")),
                (
                    "self_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "PP"), (2, "SP"), (3, "AP"), (4, "AE"), (5, "OP")],
                        null=True,
                    ),
                ),
                (
                    "supervisor_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "PP"), (2, "SP"), (3, "AP"), (4, "AE"), (5, "OP")],
                        null=True,
                    ),
                ),
                (
                    "agreed_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "PP"), (2, "SP"), (3, "AP"), (4, "AE"), (5, "OP")],
                        null=True,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_number", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPENED", "Opened"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("HEARING_PENDING", "Hearing Pending"),
                            ("INVESTIGATION_PENDING", "Investigation Pending"),
                            ("VERDICT_PENDING", "Verdict Pending"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPENED",
                        max_length=30,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("GUILTY", "Guilty"),
                            ("NOT_GUILTY", "Not Guilty"),
                            ("SETTLED", "Settled"),
                            ("DISMISSED", "Dismissed"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "charges_document",
                    models.FileField(blank=True, upload_to="cases/charges/"),
                ),
                ("charges_text", models.TextField(blank=True)),
                ("final_verdict_text", models.TextField(blank=True)),
                ("sanctions_imposed", models.TextField(blank=True)),
                ("appeal_status", models.CharField(blank=True, max_length=50)),
                ("case_opened_date", models.DateField(auto_now_add=True)),
                ("case_closed_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-case_opened_date"],
            },
        ),
        migrations.CreateModel(
            name="Hearing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hearing_number", models.CharField(max_length=100, unique=True)),
                ("hearing_date", models.DateField()),
                ("hearing_time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("HELD", "Held"),
                            ("ADJOURNED", "Adjourned"),
                            ("CONCLUDED", "Concluded"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "committee_members",
                    models.TextField(help_text="Names of committee members"),
                ),
                ("chairperson", models.CharField(blank=True, max_length=200)),
                ("charges", models.TextField()),
                (
                    "employee_statement",
                    models.TextField(
                        blank=True, help_text="Employee's response/statement"
                    ),
                ),
                ("committee_findings", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                (
                    "sanctions",
                    models.TextField(
                        blank=True, help_text="Recommended sanctions if any"
                    ),
                ),
                (
                    "hearing_document",
                    models.FileField(blank=True, upload_to="hearings/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-hearing_date"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_name", models.CharField(max_length=300)),
                ("candidate_nrc", models.CharField(blank=True, max_length=50)),
                ("position", models.CharField(max_length=200)),
                ("interview_date", models.DateField()),
                ("interview_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "committee_members",
                    models.TextField(
                        help_text="Names of committee members, comma-separated"
                    ),
                ),
                (
                    "questions",
                    models.TextField(
                        help_text="Interview questions, formatted as JSON or plain text"
                    ),
                ),
                ("final_score", models.FloatField(blank=True, null=True)),
                ("recommendations", models.TextField(blank=True)),
                (
                    "interview_document",
                    models.FileField(blank=True, upload_to="interviews/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-interview_date"],
            },
        ),
        migrations.CreateModel(
            name="Investigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("investigation_number", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("investigation_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CLOSED", "Closed"),
                        ],
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                ("investigator", models.CharField(max_length=200)),
                ("evidence_collected", models.TextField(blank=True)),
                (
                    "observations",
                    models.TextField(
                        blank=True, help_text="Observations from scene/interviews"
                    ),
                ),
                ("findings", models.TextField(blank=True)),
                (
                    "conclusion_of_scene",
                    models.TextField(
                        blank=True, help_text="Conclusion from scene analysis"
                    ),
                ),
                ("conclusions", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                (
                    "investigation_document",
                    models.FileField(blank=True, upload_to="investigations/"),
                ),
                (
                    "supporting_documents",
                    models.FileField(
                        blank=True,
                        help_text="Additional supporting documents",
                        null=True,
                        upload_to="investigations/supporting/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-investigation_date"],
            },
        ),
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kpi_name", models.CharField(max_length=200)),
                (
                    "kpi_type",
                    models.CharField(
                        choices=[
                            ("PRODUCTIVITY", "Productivity"),
                            ("ATTENDANCE", "Attendance"),
                            ("SAFETY", "Safety"),
                            ("QUALITY", "Quality"),
                            ("EFFICIENCY", "Efficiency"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="CUSTOM",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("YEARLY", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("target_value", models.FloatField()),
                ("actual_value", models.FloatField(blank=True, null=True)),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="e.g., units, %, hours", max_length=50
                    ),
                ),
                ("achieved", models.BooleanField(default=False)),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-end_date"],
            },
        ),
        migrations.CreateModel(
            name="ReportType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("SAFETY", "Safety"),
                            ("COMPLAINT", "Complaint"),
                            ("GRIEVANCE", "Grievance"),
                            ("DISCIPLINARY", "Disciplinary"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Report Types",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_number", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("location", models.CharField(blank=True, max_length=200)),
                ("incident_date", models.DateField()),
                ("incident_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("ESCALATED", "Escalated"),
                            ("CLOSED", "Closed"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("attachments", models.FileField(blank=True, upload_to="reports/")),
                ("is_escalated", models.BooleanField(default=False)),
                ("escalated_to_case", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activities.reporttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
