# Generated by Django 4.2.8 on 2026-02-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0007_link_case_study_activity_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("hearing", "Hearing"),
                            ("investigation", "Investigation"),
                            ("charge", "Charge"),
                            ("report", "Report"),
                            ("training", "Training"),
                            ("medical", "Medical"),
                            ("leave", "Leave"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("case_study", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
