# Generated by Django 4.2.8 on 2026-02-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0008_scheduleevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleevent",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="scheduleevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("hearing", "Hearing"),
                    ("investigation", "Investigation"),
                    ("charge", "Charge"),
                    ("report", "Report"),
                    ("training", "Training"),
                    ("medical", "Medical"),
                    ("leave", "Leave"),
                    ("meeting", "Meeting"),
                    ("travel", "Travel"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
