# Generated by Django 4.2.8 on 2026-03-05 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_workspace'),
        ('activities', '0009_scheduleevent_description_alter_scheduleevent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to='core.workspace'),
        ),
    ]
